# Generated by Django 5.2.5 on 2025-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('IN', 'Pay-in'), ('OUT', 'Pay-out')], default='IN', max_length=3)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
