# Generated by Django 5.2.5 on 2025-08-22 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_workrecord_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='employees.contractualemployee'),
        ),
    ]
