# Generated by Django 5.2.5 on 2025-08-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_workrecord_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractualemployee',
            name='category',
            field=models.CharField(choices=[('contractual', 'Contractual / Temp Worker'), ('fixed', 'Fixed Salary Employee')], default='contractual', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractualemployee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contractualemployee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
