# Generated by Django 5.2.5 on 2025-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_contractualemployee_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractualemployee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
