# Generated by Django 5.2.5 on 2025-08-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_contractualemployee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractualemployee',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contractualemployee',
            name='salary',
        ),
        migrations.AlterField(
            model_name='contractualemployee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractualemployee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fixedemployee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fixedemployee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fixedemployee',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
