# Generated by Django 5.2.5 on 2025-08-24 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_fixedadvancepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedemployee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fixedemployee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FixedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_payments', to='employees.fixedemployee')),
            ],
        ),
        migrations.DeleteModel(
            name='FixedAdvancePayment',
        ),
    ]
