# Generated by Django 5.2.5 on 2025-08-25 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_fixedemployee_name_alter_fixedemployee_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='employees.fixedemployee')),
            ],
        ),
    ]
