# Generated by Django 5.2.5 on 2025-08-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_fixedsalarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedsalarypayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fixed_payments', to='employees.fixedemployee'),
        ),
    ]
