# Generated by Django 5.2.5 on 2025-08-25 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_fixedsalarypayment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedsalarypayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_payments', to='employees.fixedemployee'),
        ),
        migrations.DeleteModel(
            name='FixedPayment',
        ),
    ]
