# Generated by Django 5.2.5 on 2025-08-26 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_fixedsalarypayment_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedsalarypayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
