# Generated by Django 5.2.5 on 2025-08-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_fixedsalarypayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
