# Generated by Django 5.2.5 on 2025-08-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_salarypayment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedsalarypayment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
