# Generated by Django 5.2.5 on 2025-09-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_fixedworkcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedworkcredit',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fixedworkcredit',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
