# Generated by Django 5.2.5 on 2025-09-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_fixedworkcredit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedworkcredit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fixedworkcredit',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
