# Generated by Django 5.2.5 on 2025-09-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_fixedworkcredit_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixedWorkCredit',
        ),
    ]
