# Generated by Django 5.2.5 on 2025-08-18 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('MATERIAL', 'Material Expense'), ('RBG', 'Rent / Bill / Guest'), ('SETUP', 'Setup Purchase')], max_length=20)),
                ('sub_type', models.CharField(blank=True, choices=[('RENT', 'Rent'), ('BILL', 'Bill'), ('GUEST', 'Guest')], max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
