# Generated by Django 5.2.5 on 2025-08-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MATERIAL', 'Material Expense'), ('RBG', 'Rent / Bill / Guest'), ('SETUP', 'Setup Purchase'), ('OUTSOURCE', 'Outsource'), ('LOGISTICS', 'Logistics')], max_length=20),
        ),
    ]
